runtime: python311 
handlers:
- url: /static
  static_dir: static
- url: /.*
  script: wsgi.app
  
env_variables:
  DJANGO_SETTINGS_MODULE: "myproject.settings"  
  GOOGLE_APPLICATION_CREDENTIALS: "C:\Users\cheta\Desktop\Instagram\Working\PostsGCP\cloudsql-pgsql-435413-02bc139a30b4.json" 