# Generated by Django 5.1.1 on 2024-09-15 09:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InstagramProfile',
            fields=[
                ('username', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('post_count', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='InstagramPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video'), ('carousel', 'Carousel')], default='image', max_length=10)),
                ('image', models.CharField(blank=True, max_length=100, null=True)),
                ('video', models.CharField(blank=True, max_length=100, null=True)),
                ('caption', models.TextField(blank=True, null=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='instagram.instagramprofile')),
            ],
        ),
    ]
